apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitcommits.gitwatcher.cattle.io
spec:
  group: gitwatcher.cattle.io
  version: v1
  names:
    kind: GitCommit
    plural: gitcommits
  scope: Namespaced