apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.hobbyfarm.io
spec:
  group: hobbyfarm.io
  versions:
    - name: v2
      served: true
      storage: true
    - name: v1
      served: true
      storage: false
  names:
    kind: User
    plural: users
  scope: Cluster