// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: hobbyfarm/dynamicbindconfiguration_service.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DynamicBindConfigurationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicBindConfigurations []*DynamicBindConfiguration `protobuf:"bytes,1,rep,name=DynamicBindConfigurations,proto3" json:"DynamicBindConfigurations,omitempty"`
}

func (x *DynamicBindConfigurationList) Reset() {
	*x = DynamicBindConfigurationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hobbyfarm_dynamicbindconfiguration_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicBindConfigurationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicBindConfigurationList) ProtoMessage() {}

func (x *DynamicBindConfigurationList) ProtoReflect() protoreflect.Message {
	mi := &file_hobbyfarm_dynamicbindconfiguration_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicBindConfigurationList.ProtoReflect.Descriptor instead.
func (*DynamicBindConfigurationList) Descriptor() ([]byte, []int) {
	return file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicBindConfigurationList) GetDynamicBindConfigurations() []*DynamicBindConfiguration {
	if x != nil {
		return x.DynamicBindConfigurations
	}
	return nil
}

var File_hobbyfarm_dynamicbindconfiguration_service_proto protoreflect.FileDescriptor

var file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDesc = []byte{
	0x0a, 0x30, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x62, 0x69, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x19, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62,
	0x79, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x1c, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x57, 0x0a, 0x19, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x19, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x32, 0xfc, 0x03, 0x0a, 0x1f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x12,
	0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x62, 0x69, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x55, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x19,
	0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x28, 0x12, 0x26, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x62, 0x69, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x12, 0x6c, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19,
	0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x26, 0x22, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x62, 0x69, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x73, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x2e, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2d, 0x1a,
	0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x62, 0x69, 0x6e, 0x64, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x7b, 0x4e, 0x61, 0x6d, 0x65, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x45, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x2a, 0x26, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x62, 0x69, 0x6e, 0x64,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x7b,
	0x49, 0x44, 0x7d, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x67, 0x61, 0x72, 0x67,
	0x61, 0x6e, 0x74, 0x75, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescOnce sync.Once
	file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescData = file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDesc
)

func file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescGZIP() []byte {
	file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescOnce.Do(func() {
		file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescData)
	})
	return file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDescData
}

var file_hobbyfarm_dynamicbindconfiguration_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hobbyfarm_dynamicbindconfiguration_service_proto_goTypes = []interface{}{
	(*DynamicBindConfigurationList)(nil), // 0: DynamicBindConfigurationList
	(*DynamicBindConfiguration)(nil),     // 1: DynamicBindConfiguration
	(*Empty)(nil),                        // 2: Empty
	(*ID)(nil),                           // 3: ID
}
var file_hobbyfarm_dynamicbindconfiguration_service_proto_depIdxs = []int32{
	1, // 0: DynamicBindConfigurationList.DynamicBindConfigurations:type_name -> DynamicBindConfiguration
	2, // 1: DynamicBindConfigurationService.List:input_type -> Empty
	3, // 2: DynamicBindConfigurationService.Get:input_type -> ID
	1, // 3: DynamicBindConfigurationService.Create:input_type -> DynamicBindConfiguration
	1, // 4: DynamicBindConfigurationService.Update:input_type -> DynamicBindConfiguration
	3, // 5: DynamicBindConfigurationService.Delete:input_type -> ID
	0, // 6: DynamicBindConfigurationService.List:output_type -> DynamicBindConfigurationList
	1, // 7: DynamicBindConfigurationService.Get:output_type -> DynamicBindConfiguration
	1, // 8: DynamicBindConfigurationService.Create:output_type -> DynamicBindConfiguration
	1, // 9: DynamicBindConfigurationService.Update:output_type -> DynamicBindConfiguration
	2, // 10: DynamicBindConfigurationService.Delete:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hobbyfarm_dynamicbindconfiguration_service_proto_init() }
func file_hobbyfarm_dynamicbindconfiguration_service_proto_init() {
	if File_hobbyfarm_dynamicbindconfiguration_service_proto != nil {
		return
	}
	file_hobbyfarm_hobbyfarm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hobbyfarm_dynamicbindconfiguration_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicBindConfigurationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hobbyfarm_dynamicbindconfiguration_service_proto_goTypes,
		DependencyIndexes: file_hobbyfarm_dynamicbindconfiguration_service_proto_depIdxs,
		MessageInfos:      file_hobbyfarm_dynamicbindconfiguration_service_proto_msgTypes,
	}.Build()
	File_hobbyfarm_dynamicbindconfiguration_service_proto = out.File
	file_hobbyfarm_dynamicbindconfiguration_service_proto_rawDesc = nil
	file_hobbyfarm_dynamicbindconfiguration_service_proto_goTypes = nil
	file_hobbyfarm_dynamicbindconfiguration_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DynamicBindConfigurationServiceClient is the client API for DynamicBindConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DynamicBindConfigurationServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DynamicBindConfigurationList, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DynamicBindConfiguration, error)
	Create(ctx context.Context, in *DynamicBindConfiguration, opts ...grpc.CallOption) (*DynamicBindConfiguration, error)
	Update(ctx context.Context, in *DynamicBindConfiguration, opts ...grpc.CallOption) (*DynamicBindConfiguration, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type dynamicBindConfigurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicBindConfigurationServiceClient(cc grpc.ClientConnInterface) DynamicBindConfigurationServiceClient {
	return &dynamicBindConfigurationServiceClient{cc}
}

func (c *dynamicBindConfigurationServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DynamicBindConfigurationList, error) {
	out := new(DynamicBindConfigurationList)
	err := c.cc.Invoke(ctx, "/DynamicBindConfigurationService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicBindConfigurationServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DynamicBindConfiguration, error) {
	out := new(DynamicBindConfiguration)
	err := c.cc.Invoke(ctx, "/DynamicBindConfigurationService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicBindConfigurationServiceClient) Create(ctx context.Context, in *DynamicBindConfiguration, opts ...grpc.CallOption) (*DynamicBindConfiguration, error) {
	out := new(DynamicBindConfiguration)
	err := c.cc.Invoke(ctx, "/DynamicBindConfigurationService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicBindConfigurationServiceClient) Update(ctx context.Context, in *DynamicBindConfiguration, opts ...grpc.CallOption) (*DynamicBindConfiguration, error) {
	out := new(DynamicBindConfiguration)
	err := c.cc.Invoke(ctx, "/DynamicBindConfigurationService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicBindConfigurationServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/DynamicBindConfigurationService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicBindConfigurationServiceServer is the server API for DynamicBindConfigurationService service.
type DynamicBindConfigurationServiceServer interface {
	List(context.Context, *Empty) (*DynamicBindConfigurationList, error)
	Get(context.Context, *ID) (*DynamicBindConfiguration, error)
	Create(context.Context, *DynamicBindConfiguration) (*DynamicBindConfiguration, error)
	Update(context.Context, *DynamicBindConfiguration) (*DynamicBindConfiguration, error)
	Delete(context.Context, *ID) (*Empty, error)
}

// UnimplementedDynamicBindConfigurationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDynamicBindConfigurationServiceServer struct {
}

func (*UnimplementedDynamicBindConfigurationServiceServer) List(context.Context, *Empty) (*DynamicBindConfigurationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedDynamicBindConfigurationServiceServer) Get(context.Context, *ID) (*DynamicBindConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDynamicBindConfigurationServiceServer) Create(context.Context, *DynamicBindConfiguration) (*DynamicBindConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDynamicBindConfigurationServiceServer) Update(context.Context, *DynamicBindConfiguration) (*DynamicBindConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedDynamicBindConfigurationServiceServer) Delete(context.Context, *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterDynamicBindConfigurationServiceServer(s *grpc.Server, srv DynamicBindConfigurationServiceServer) {
	s.RegisterService(&_DynamicBindConfigurationService_serviceDesc, srv)
}

func _DynamicBindConfigurationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicBindConfigurationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DynamicBindConfigurationService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicBindConfigurationServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicBindConfigurationService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicBindConfigurationServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DynamicBindConfigurationService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicBindConfigurationServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicBindConfigurationService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicBindConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicBindConfigurationServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DynamicBindConfigurationService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicBindConfigurationServiceServer).Create(ctx, req.(*DynamicBindConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicBindConfigurationService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicBindConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicBindConfigurationServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DynamicBindConfigurationService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicBindConfigurationServiceServer).Update(ctx, req.(*DynamicBindConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicBindConfigurationService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicBindConfigurationServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DynamicBindConfigurationService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicBindConfigurationServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _DynamicBindConfigurationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DynamicBindConfigurationService",
	HandlerType: (*DynamicBindConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DynamicBindConfigurationService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DynamicBindConfigurationService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DynamicBindConfigurationService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DynamicBindConfigurationService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DynamicBindConfigurationService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hobbyfarm/dynamicbindconfiguration_service.proto",
}
