// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: hobbyfarm/scheduledevent_service.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ScheduledEventList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduledEvents []*ScheduledEvent `protobuf:"bytes,1,rep,name=ScheduledEvents,proto3" json:"ScheduledEvents,omitempty"`
}

func (x *ScheduledEventList) Reset() {
	*x = ScheduledEventList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hobbyfarm_scheduledevent_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduledEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledEventList) ProtoMessage() {}

func (x *ScheduledEventList) ProtoReflect() protoreflect.Message {
	mi := &file_hobbyfarm_scheduledevent_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledEventList.ProtoReflect.Descriptor instead.
func (*ScheduledEventList) Descriptor() ([]byte, []int) {
	return file_hobbyfarm_scheduledevent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledEventList) GetScheduledEvents() []*ScheduledEvent {
	if x != nil {
		return x.ScheduledEvents
	}
	return nil
}

var File_hobbyfarm_scheduledevent_service_proto protoreflect.FileDescriptor

var file_hobbyfarm_scheduledevent_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72,
	0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4f, 0x0a, 0x12, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0x84, 0x03, 0x0a, 0x15, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x32, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x41, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x0f,
	0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32,
	0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x12, 0x4e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x0f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x1a, 0x0f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x32, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x55, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x0f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x1a, 0x0f, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x1a, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x32, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x7b, 0x4e, 0x61, 0x6d, 0x65, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x3b, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x2a, 0x1c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72,
	0x6d, 0x2f, 0x67, 0x61, 0x72, 0x67, 0x61, 0x6e, 0x74, 0x75, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hobbyfarm_scheduledevent_service_proto_rawDescOnce sync.Once
	file_hobbyfarm_scheduledevent_service_proto_rawDescData = file_hobbyfarm_scheduledevent_service_proto_rawDesc
)

func file_hobbyfarm_scheduledevent_service_proto_rawDescGZIP() []byte {
	file_hobbyfarm_scheduledevent_service_proto_rawDescOnce.Do(func() {
		file_hobbyfarm_scheduledevent_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hobbyfarm_scheduledevent_service_proto_rawDescData)
	})
	return file_hobbyfarm_scheduledevent_service_proto_rawDescData
}

var file_hobbyfarm_scheduledevent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hobbyfarm_scheduledevent_service_proto_goTypes = []interface{}{
	(*ScheduledEventList)(nil), // 0: ScheduledEventList
	(*ScheduledEvent)(nil),     // 1: ScheduledEvent
	(*Empty)(nil),              // 2: Empty
	(*ID)(nil),                 // 3: ID
}
var file_hobbyfarm_scheduledevent_service_proto_depIdxs = []int32{
	1, // 0: ScheduledEventList.ScheduledEvents:type_name -> ScheduledEvent
	2, // 1: ScheduledEventService.List:input_type -> Empty
	3, // 2: ScheduledEventService.Get:input_type -> ID
	1, // 3: ScheduledEventService.Create:input_type -> ScheduledEvent
	1, // 4: ScheduledEventService.Update:input_type -> ScheduledEvent
	3, // 5: ScheduledEventService.Delete:input_type -> ID
	0, // 6: ScheduledEventService.List:output_type -> ScheduledEventList
	1, // 7: ScheduledEventService.Get:output_type -> ScheduledEvent
	1, // 8: ScheduledEventService.Create:output_type -> ScheduledEvent
	1, // 9: ScheduledEventService.Update:output_type -> ScheduledEvent
	2, // 10: ScheduledEventService.Delete:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hobbyfarm_scheduledevent_service_proto_init() }
func file_hobbyfarm_scheduledevent_service_proto_init() {
	if File_hobbyfarm_scheduledevent_service_proto != nil {
		return
	}
	file_hobbyfarm_hobbyfarm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hobbyfarm_scheduledevent_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduledEventList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hobbyfarm_scheduledevent_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hobbyfarm_scheduledevent_service_proto_goTypes,
		DependencyIndexes: file_hobbyfarm_scheduledevent_service_proto_depIdxs,
		MessageInfos:      file_hobbyfarm_scheduledevent_service_proto_msgTypes,
	}.Build()
	File_hobbyfarm_scheduledevent_service_proto = out.File
	file_hobbyfarm_scheduledevent_service_proto_rawDesc = nil
	file_hobbyfarm_scheduledevent_service_proto_goTypes = nil
	file_hobbyfarm_scheduledevent_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ScheduledEventServiceClient is the client API for ScheduledEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScheduledEventServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScheduledEventList, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ScheduledEvent, error)
	Create(ctx context.Context, in *ScheduledEvent, opts ...grpc.CallOption) (*ScheduledEvent, error)
	Update(ctx context.Context, in *ScheduledEvent, opts ...grpc.CallOption) (*ScheduledEvent, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type scheduledEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduledEventServiceClient(cc grpc.ClientConnInterface) ScheduledEventServiceClient {
	return &scheduledEventServiceClient{cc}
}

func (c *scheduledEventServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScheduledEventList, error) {
	out := new(ScheduledEventList)
	err := c.cc.Invoke(ctx, "/ScheduledEventService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledEventServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ScheduledEvent, error) {
	out := new(ScheduledEvent)
	err := c.cc.Invoke(ctx, "/ScheduledEventService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledEventServiceClient) Create(ctx context.Context, in *ScheduledEvent, opts ...grpc.CallOption) (*ScheduledEvent, error) {
	out := new(ScheduledEvent)
	err := c.cc.Invoke(ctx, "/ScheduledEventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledEventServiceClient) Update(ctx context.Context, in *ScheduledEvent, opts ...grpc.CallOption) (*ScheduledEvent, error) {
	out := new(ScheduledEvent)
	err := c.cc.Invoke(ctx, "/ScheduledEventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledEventServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ScheduledEventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduledEventServiceServer is the server API for ScheduledEventService service.
type ScheduledEventServiceServer interface {
	List(context.Context, *Empty) (*ScheduledEventList, error)
	Get(context.Context, *ID) (*ScheduledEvent, error)
	Create(context.Context, *ScheduledEvent) (*ScheduledEvent, error)
	Update(context.Context, *ScheduledEvent) (*ScheduledEvent, error)
	Delete(context.Context, *ID) (*Empty, error)
}

// UnimplementedScheduledEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedScheduledEventServiceServer struct {
}

func (*UnimplementedScheduledEventServiceServer) List(context.Context, *Empty) (*ScheduledEventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedScheduledEventServiceServer) Get(context.Context, *ID) (*ScheduledEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedScheduledEventServiceServer) Create(context.Context, *ScheduledEvent) (*ScheduledEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedScheduledEventServiceServer) Update(context.Context, *ScheduledEvent) (*ScheduledEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedScheduledEventServiceServer) Delete(context.Context, *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterScheduledEventServiceServer(s *grpc.Server, srv ScheduledEventServiceServer) {
	s.RegisterService(&_ScheduledEventService_serviceDesc, srv)
}

func _ScheduledEventService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledEventServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScheduledEventService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledEventServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledEventService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledEventServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScheduledEventService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledEventServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledEventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduledEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledEventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScheduledEventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledEventServiceServer).Create(ctx, req.(*ScheduledEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledEventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduledEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledEventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScheduledEventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledEventServiceServer).Update(ctx, req.(*ScheduledEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledEventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledEventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScheduledEventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledEventServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScheduledEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ScheduledEventService",
	HandlerType: (*ScheduledEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ScheduledEventService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ScheduledEventService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ScheduledEventService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ScheduledEventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ScheduledEventService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hobbyfarm/scheduledevent_service.proto",
}
