// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: hobbyfarm/virtualmachineset_service.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VirtualMachineSetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualMachineSets []*VirtualMachineSet `protobuf:"bytes,1,rep,name=VirtualMachineSets,proto3" json:"VirtualMachineSets,omitempty"`
}

func (x *VirtualMachineSetList) Reset() {
	*x = VirtualMachineSetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hobbyfarm_virtualmachineset_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineSetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineSetList) ProtoMessage() {}

func (x *VirtualMachineSetList) ProtoReflect() protoreflect.Message {
	mi := &file_hobbyfarm_virtualmachineset_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineSetList.ProtoReflect.Descriptor instead.
func (*VirtualMachineSetList) Descriptor() ([]byte, []int) {
	return file_hobbyfarm_virtualmachineset_service_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachineSetList) GetVirtualMachineSets() []*VirtualMachineSet {
	if x != nil {
		return x.VirtualMachineSets
	}
	return nil
}

var File_hobbyfarm_virtualmachineset_service_proto protoreflect.FileDescriptor

var file_hobbyfarm_virtualmachineset_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x76, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x68, 0x6f, 0x62, 0x62, 0x79,
	0x66, 0x61, 0x72, 0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x15, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x42, 0x0a,
	0x12, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53,
	0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x52, 0x12, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74,
	0x73, 0x32, 0xa8, 0x03, 0x0a, 0x18, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x7b,
	0x49, 0x44, 0x7d, 0x12, 0x57, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65,
	0x74, 0x1a, 0x12, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x53, 0x65, 0x74, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1a, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x5e, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x22, 0x2c,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x1a, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65,
	0x74, 0x73, 0x2f, 0x7b, 0x4e, 0x61, 0x6d, 0x65, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x3e, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x2a, 0x1f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x62, 0x62, 0x79,
	0x66, 0x61, 0x72, 0x6d, 0x2f, 0x67, 0x61, 0x72, 0x67, 0x61, 0x6e, 0x74, 0x75, 0x61, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_hobbyfarm_virtualmachineset_service_proto_rawDescOnce sync.Once
	file_hobbyfarm_virtualmachineset_service_proto_rawDescData = file_hobbyfarm_virtualmachineset_service_proto_rawDesc
)

func file_hobbyfarm_virtualmachineset_service_proto_rawDescGZIP() []byte {
	file_hobbyfarm_virtualmachineset_service_proto_rawDescOnce.Do(func() {
		file_hobbyfarm_virtualmachineset_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hobbyfarm_virtualmachineset_service_proto_rawDescData)
	})
	return file_hobbyfarm_virtualmachineset_service_proto_rawDescData
}

var file_hobbyfarm_virtualmachineset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hobbyfarm_virtualmachineset_service_proto_goTypes = []interface{}{
	(*VirtualMachineSetList)(nil), // 0: VirtualMachineSetList
	(*VirtualMachineSet)(nil),     // 1: VirtualMachineSet
	(*Empty)(nil),                 // 2: Empty
	(*ID)(nil),                    // 3: ID
}
var file_hobbyfarm_virtualmachineset_service_proto_depIdxs = []int32{
	1, // 0: VirtualMachineSetList.VirtualMachineSets:type_name -> VirtualMachineSet
	2, // 1: VirtualMachineSetService.List:input_type -> Empty
	3, // 2: VirtualMachineSetService.Get:input_type -> ID
	1, // 3: VirtualMachineSetService.Create:input_type -> VirtualMachineSet
	1, // 4: VirtualMachineSetService.Update:input_type -> VirtualMachineSet
	3, // 5: VirtualMachineSetService.Delete:input_type -> ID
	0, // 6: VirtualMachineSetService.List:output_type -> VirtualMachineSetList
	1, // 7: VirtualMachineSetService.Get:output_type -> VirtualMachineSet
	1, // 8: VirtualMachineSetService.Create:output_type -> VirtualMachineSet
	1, // 9: VirtualMachineSetService.Update:output_type -> VirtualMachineSet
	2, // 10: VirtualMachineSetService.Delete:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hobbyfarm_virtualmachineset_service_proto_init() }
func file_hobbyfarm_virtualmachineset_service_proto_init() {
	if File_hobbyfarm_virtualmachineset_service_proto != nil {
		return
	}
	file_hobbyfarm_hobbyfarm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hobbyfarm_virtualmachineset_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineSetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hobbyfarm_virtualmachineset_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hobbyfarm_virtualmachineset_service_proto_goTypes,
		DependencyIndexes: file_hobbyfarm_virtualmachineset_service_proto_depIdxs,
		MessageInfos:      file_hobbyfarm_virtualmachineset_service_proto_msgTypes,
	}.Build()
	File_hobbyfarm_virtualmachineset_service_proto = out.File
	file_hobbyfarm_virtualmachineset_service_proto_rawDesc = nil
	file_hobbyfarm_virtualmachineset_service_proto_goTypes = nil
	file_hobbyfarm_virtualmachineset_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VirtualMachineSetServiceClient is the client API for VirtualMachineSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineSetServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VirtualMachineSetList, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VirtualMachineSet, error)
	Create(ctx context.Context, in *VirtualMachineSet, opts ...grpc.CallOption) (*VirtualMachineSet, error)
	Update(ctx context.Context, in *VirtualMachineSet, opts ...grpc.CallOption) (*VirtualMachineSet, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type virtualMachineSetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualMachineSetServiceClient(cc grpc.ClientConnInterface) VirtualMachineSetServiceClient {
	return &virtualMachineSetServiceClient{cc}
}

func (c *virtualMachineSetServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VirtualMachineSetList, error) {
	out := new(VirtualMachineSetList)
	err := c.cc.Invoke(ctx, "/VirtualMachineSetService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSetServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VirtualMachineSet, error) {
	out := new(VirtualMachineSet)
	err := c.cc.Invoke(ctx, "/VirtualMachineSetService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSetServiceClient) Create(ctx context.Context, in *VirtualMachineSet, opts ...grpc.CallOption) (*VirtualMachineSet, error) {
	out := new(VirtualMachineSet)
	err := c.cc.Invoke(ctx, "/VirtualMachineSetService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSetServiceClient) Update(ctx context.Context, in *VirtualMachineSet, opts ...grpc.CallOption) (*VirtualMachineSet, error) {
	out := new(VirtualMachineSet)
	err := c.cc.Invoke(ctx, "/VirtualMachineSetService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineSetServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/VirtualMachineSetService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineSetServiceServer is the server API for VirtualMachineSetService service.
type VirtualMachineSetServiceServer interface {
	List(context.Context, *Empty) (*VirtualMachineSetList, error)
	Get(context.Context, *ID) (*VirtualMachineSet, error)
	Create(context.Context, *VirtualMachineSet) (*VirtualMachineSet, error)
	Update(context.Context, *VirtualMachineSet) (*VirtualMachineSet, error)
	Delete(context.Context, *ID) (*Empty, error)
}

// UnimplementedVirtualMachineSetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineSetServiceServer struct {
}

func (*UnimplementedVirtualMachineSetServiceServer) List(context.Context, *Empty) (*VirtualMachineSetList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedVirtualMachineSetServiceServer) Get(context.Context, *ID) (*VirtualMachineSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedVirtualMachineSetServiceServer) Create(context.Context, *VirtualMachineSet) (*VirtualMachineSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedVirtualMachineSetServiceServer) Update(context.Context, *VirtualMachineSet) (*VirtualMachineSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedVirtualMachineSetServiceServer) Delete(context.Context, *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterVirtualMachineSetServiceServer(s *grpc.Server, srv VirtualMachineSetServiceServer) {
	s.RegisterService(&_VirtualMachineSetService_serviceDesc, srv)
}

func _VirtualMachineSetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VirtualMachineSetService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSetServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VirtualMachineSetService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSetServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSetService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSetServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VirtualMachineSetService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSetServiceServer).Create(ctx, req.(*VirtualMachineSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSetService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSetServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VirtualMachineSetService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSetServiceServer).Update(ctx, req.(*VirtualMachineSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineSetService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineSetServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VirtualMachineSetService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineSetServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineSetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VirtualMachineSetService",
	HandlerType: (*VirtualMachineSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _VirtualMachineSetService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VirtualMachineSetService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VirtualMachineSetService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VirtualMachineSetService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VirtualMachineSetService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hobbyfarm/virtualmachineset_service.proto",
}
