/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/pkg/apis/hobbyfarm.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContentRepositories implements ContentRepositoryInterface
type FakeContentRepositories struct {
	Fake *FakeHobbyfarmV1
}

var contentrepositoriesResource = schema.GroupVersionResource{Group: "hobbyfarm.io", Version: "v1", Resource: "contentrepositories"}

var contentrepositoriesKind = schema.GroupVersionKind{Group: "hobbyfarm.io", Version: "v1", Kind: "ContentRepository"}

// Get takes name of the contentRepository, and returns the corresponding contentRepository object, and an error if there is any.
func (c *FakeContentRepositories) Get(name string, options v1.GetOptions) (result *hobbyfarmiov1.ContentRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(contentrepositoriesResource, name), &hobbyfarmiov1.ContentRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.ContentRepository), err
}

// List takes label and field selectors, and returns the list of ContentRepositories that match those selectors.
func (c *FakeContentRepositories) List(opts v1.ListOptions) (result *hobbyfarmiov1.ContentRepositoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(contentrepositoriesResource, contentrepositoriesKind, opts), &hobbyfarmiov1.ContentRepositoryList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hobbyfarmiov1.ContentRepositoryList{ListMeta: obj.(*hobbyfarmiov1.ContentRepositoryList).ListMeta}
	for _, item := range obj.(*hobbyfarmiov1.ContentRepositoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested contentRepositories.
func (c *FakeContentRepositories) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(contentrepositoriesResource, opts))
}

// Create takes the representation of a contentRepository and creates it.  Returns the server's representation of the contentRepository, and an error, if there is any.
func (c *FakeContentRepositories) Create(contentRepository *hobbyfarmiov1.ContentRepository) (result *hobbyfarmiov1.ContentRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(contentrepositoriesResource, contentRepository), &hobbyfarmiov1.ContentRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.ContentRepository), err
}

// Update takes the representation of a contentRepository and updates it. Returns the server's representation of the contentRepository, and an error, if there is any.
func (c *FakeContentRepositories) Update(contentRepository *hobbyfarmiov1.ContentRepository) (result *hobbyfarmiov1.ContentRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(contentrepositoriesResource, contentRepository), &hobbyfarmiov1.ContentRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.ContentRepository), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeContentRepositories) UpdateStatus(contentRepository *hobbyfarmiov1.ContentRepository) (*hobbyfarmiov1.ContentRepository, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(contentrepositoriesResource, "status", contentRepository), &hobbyfarmiov1.ContentRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.ContentRepository), err
}

// Delete takes name of the contentRepository and deletes it. Returns an error if one occurs.
func (c *FakeContentRepositories) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(contentrepositoriesResource, name), &hobbyfarmiov1.ContentRepository{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContentRepositories) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(contentrepositoriesResource, listOptions)

	_, err := c.Fake.Invokes(action, &hobbyfarmiov1.ContentRepositoryList{})
	return err
}

// Patch applies the patch and returns the patched contentRepository.
func (c *FakeContentRepositories) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hobbyfarmiov1.ContentRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(contentrepositoriesResource, name, pt, data, subresources...), &hobbyfarmiov1.ContentRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.ContentRepository), err
}
