name: Main
on: [push, pull_request]
jobs:
  build-gargantua:
    uses: ./.github/workflows/build.yaml
    with:
      path: ./
      image: gargantua
    secrets: inherit
  build-user-service:
    uses: ./.github/workflows/build.yaml
    with:
      path: ./services/usersvc
      image: userservice
    secrets: inherit